# Generated by Django 6.0.1 on 2026-01-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterresume',
            name='latex_template',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterresume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
