# Generated by Django 6.0.1 on 2026-01-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_masterresume_latex_source'),
        ('applications', '0002_tailored_resume_client_id_and_timestamps'),
    ]

    operations = [
    ]
