# Generated by Django 6.0.1 on 2026-01-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_tailoredresume_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
