# Generated by Django 6.0.1 on 2026-01-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_jobapplication_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterresume',
            name='latex_source',
            field=models.TextField(default=''),
        ),
    ]
