# Generated by Django 4.2.10 on 2026-01-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_jobapplication_add_fields'),
        ('applications', '0005_jobapplication_updated_at'),
    ]

    operations = [
    ]
