# Generated by Django 4.2.10 on 2026-01-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_masterresume_latex_source'),
        ('applications', '0006_merge_20260118_0504'),
    ]

    operations = [
    ]
