# Generated by Django 4.2.10 on 2026-01-18 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0006_alter_masterresume_latex_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="commlog",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
