# Generated by Django 6.0.1 on 2026-01-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_merge_20260118_0534'),
        ('applications', '0008_merge_0007_commlog_timestamp_0007_merge_20260118_0554'),
    ]

    operations = [
    ]
