# Generated by Django 6.0.1 on 2026-01-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_merge_20260118_1100'),
        ('applications', '0009_merge_20260118_1743'),
    ]

    operations = [
    ]
