# Generated by Django 6.0.1 on 2026-01-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobapplication_alter_masterresume_user_commlog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterresume',
            old_name='latex_template',
            new_name='latex_source',
        ),
    ]
